### ISSUE TITLE
Default to speaker off

### ISSUE THREAD

**Issue by Bytemarks** [bradbaris/coral-spaceapps#12]
Can we set the intro video with Sam Gon and me to "speaker off" as default when visiting the site? The video can run but the viewer needs to turn their speaker volume up. Much like how Facebook video works.

**Comment by yukio808** [comment]
Should be a simple change. Just add player.muted = true; or player.mute()to bind on some element

**Comment by bradbaris** [comment]
Fixed in a96874d7ae6a51522047707733d2b72eb30c320b

Yep, pretty much. Had to do some fiddling to change the hardcoded youtube iframe to an iframe generated by the YouTube API (and controlled via JS), so we could access the `mute()` function.

See: https://developers.google.com/youtube/iframe_api_reference#mute
